steps:
  # 1. Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: [
      "build", "-t",
      "us-central1-docker.pkg.dev/bubbly-upgrade-441904-p6/langbot-repo/langbot-backend-service:$COMMIT_SHA",
      "."
    ]

  # 2. Push the container image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args: [
      "push",
      "us-central1-docker.pkg.dev/bubbly-upgrade-441904-p6/langbot-repo/langbot-backend-service:$COMMIT_SHA"
    ]

  # 3. Deploy to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run", "deploy", "langbot-backend-service",
        "--image=us-central1-docker.pkg.dev/bubbly-upgrade-441904-p6/langbot-repo/langbot-backend-service:$COMMIT_SHA",
        "--region=us-central1",
        "--platform=managed",
        "--allow-unauthenticated",
        "--service-account=chatbot-run-identity@bubbly-upgrade-441904-p6.iam.gserviceaccount.com",
        "--memory=1Gi",
        "--timeout=300s"
      ]

images:
  - "us-central1-docker.pkg.dev/bubbly-upgrade-441904-p6/langbot-repo/langbot-backend-service:$COMMIT_SHA"

options:
  logging: CLOUD_LOGGING_ONLY
